[package]
name = "my-gtk-app"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk = { version = "0.9.7", package = "gtk4", features = ["v4_8"] }
glib = "0.19.7"
reqwest = "0.12.5"
tokio = { version = "1", features = ["full"] }
bytes = "1.6.0"
